### ISSUE TITLE
Difference between this plugin and EndOfFile Newline?

### ISSUE THREAD

**Issue by bcomnes** [briandipalma/esformatter-eol-last#2]
Is there a difference between what this plugin does and what this might do directly in the esformatter config?

``` json
"lineBreak" : {
    "value" : "\n",

    "before" : {
      "EndOfFile" : 1
    }
}
```

**Comment by briandipalma** [comment]
No idea as I didn't know `EndOfFile` even existed before I created this. This plugin might be totally useless if so!

**Comment by bcomnes** [comment]
Maybe esformatter didn't have an EndOfFile when you started?   I'm just diving in myself.
